{
    'name': 'Kartu Keluarga',
    'version': '1.1',
    'summary': 'kartu keluarga application software system',
    'sequence': 1,
    'description': """kartu keluarga application for odoo""",
    'category': 'kartu keluarga',
    'website': 'https://www.odoohospi.tech',
    'depends': [],
    'data': [
        "security/ir.model.access.csv",
        "data/sequence.xml",
        # "data/config_wilayah/res_country_state.xml",
        # "data/config_wilayah/res_city.xml",
        # "data/config_wilayah/res_kecamatan.xml",
        # "data/config_wilayah/res_kelurahan/res_kelurahan_part1.xml",
        # "data/config_wilayah/res_kelurahan/res_kelurahan_part2.xml",
        # "data/config_wilayah/res_kelurahan/res_kelurahan_part3.xml",
        # "data/config_wilayah/res_kelurahan/res_kelurahan_part4.xml",
        # "data/config_wilayah/res_kelurahan/res_kelurahan_part5.xml",
        # "data/config_wilayah/res_kelurahan/res_kelurahan_part6.xml",
        # "data/config_wilayah/res_kelurahan/res_kelurahan_part7.xml",
        # "data/config_wilayah/res_kelurahan/res_kelurahan_part8.xml",
        # "data/config_wilayah/res_kelurahan/res_kelurahan_part9.xml",
        # "data/config_wilayah/res_kelurahan/res_kelurahan_part10.xml",
        # "data/config_wilayah/res_kelurahan/res_kelurahan_part11.xml",
        # "data/config_wilayah/res_kelurahan/res_kelurahan_part12.xml",
        # "data/config_wilayah/res_kelurahan/res_kelurahan_part13.xml",
        "views/partner_view.xml",
        "views/config_wilayah_view.xml",
        "views/kartu_keluarga_view.xml",
    ],
    'demo': [],
    'qweb': [],
    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'LGPL-3',
}
